(lang dune 3.11)
(name flags2env)
(version 0.1.0)
(generate_opam_files true)
(source
 (github flags-2-env/flags-2-env))
(license MIT)
(authors ORESoftware)
(package
 (name flags2env)
 (synopsis "OCaml bindings for flags2env")
 (depends
  ocaml
  dune
  ctypes
  ctypes-foreign
  yojson))
