(lang dune 3.11)
(name flags2env_reason)
(version 0.1.0)
(source
 (github flags-2-env/flags-2-env))
(license MIT)
(authors ORESoftware)
(package
 (name flags2env-reason)
 (synopsis "ReasonML facade for flags2env")
 (depends
  ocaml
  dune
  reason
  flags2env))
