//! Generate Rust configuration types and JSON Schema from `.cli-flags.toml`.
//!
//! This crate calls the same native generator used by `flags2env generate`.
//! It does not maintain a second TOML parser, type mapping, or default table.
//! Use it as a build dependency; keep `flags2env` at the runtime argv boundary.

use std::collections::BTreeMap;
use std::error::Error;
use std::ffi::{CStr, CString};
use std::fs;
use std::io::{Error as IoError, ErrorKind};
use std::os::raw::c_char;
use std::path::{Path, PathBuf};

unsafe extern "C" {
    fn f2e_generate_types_from_file(
        config_path: *const c_char,
        language: *const c_char,
        type_name: *const c_char,
    ) -> *mut c_char;
    fn f2e_free(value: *mut c_char);
}

/// Supported build products. Language names cannot come from untrusted input.
#[derive(Clone, Copy, Debug)]
pub enum Language {
    /// A serde-serializable Rust structure.
    Rust,
    /// The generated JSON Schema projection, not a replacement for an
    /// independently authored application contract.
    JsonSchema,
}

/// Paths generated by [`generate_into`].
#[derive(Debug)]
pub struct GeneratedFiles {
    /// Include inside a module with `include!`.
    pub rust: PathBuf,
    /// Disposable schema projection for parity checking and inspection.
    pub schema: PathBuf,
    /// Exact build input, suitable for embedding in the executable.
    pub contract: PathBuf,
}

/// The native contract model intentionally permits the same env key to be
/// exposed by distinct command scopes. That is how compatibility spellings can
/// project onto one canonical value. A Rust struct, however, may contain the
/// field only once.
///
/// Keep the native parser/code generator authoritative: this function does not
/// parse TOML or infer types. It only coalesces byte-compatible generated Rust
/// fields. If two declarations generate different Rust field contracts (type,
/// required/optional shape, or serde field attributes), generation fails closed
/// instead of silently choosing one declaration.
fn coalesce_compatible_rust_fields(source: &str) -> Result<String, Box<dyn Error>> {
    let mut output = String::with_capacity(source.len());
    let mut pending_attributes = Vec::<String>::new();
    let mut seen = BTreeMap::<String, (String, String)>::new();

    for line in source.split_inclusive('\n') {
        let bare = line.strip_suffix('\n').unwrap_or(line);
        if bare.starts_with("    #[serde(") {
            pending_attributes.push(line.to_owned());
            continue;
        }

        if let Some(field) = bare.strip_prefix("    pub ") {
            let (name, tail) = field.split_once(':').ok_or_else(|| {
                IoError::new(
                    ErrorKind::InvalidData,
                    "flags2env generated a Rust public field without a type separator",
                )
            })?;
            if name.is_empty()
                || !name
                    .bytes()
                    .all(|byte| byte.is_ascii_alphanumeric() || byte == b'_')
            {
                return Err(IoError::new(
                    ErrorKind::InvalidData,
                    "flags2env generated an invalid Rust field identifier",
                )
                .into());
            }

            let attributes = pending_attributes.concat();
            let signature = tail.trim().to_owned();
            match seen.get(name) {
                Some((previous_attributes, previous_signature))
                    if previous_attributes == &attributes && previous_signature == &signature =>
                {
                    pending_attributes.clear();
                    continue;
                }
                Some(_) => {
                    return Err(IoError::new(
                        ErrorKind::InvalidData,
                        format!(
                            "env {name} is declared in multiple command scopes with incompatible generated Rust contracts; shared env declarations must agree on type and optionality"
                        ),
                    )
                    .into());
                }
                None => {
                    seen.insert(name.to_owned(), (attributes.clone(), signature));
                    for attribute in pending_attributes.drain(..) {
                        output.push_str(&attribute);
                    }
                    output.push_str(line);
                    continue;
                }
            }
        }

        for attribute in pending_attributes.drain(..) {
            output.push_str(&attribute);
        }
        output.push_str(line);
    }

    for attribute in pending_attributes {
        output.push_str(&attribute);
    }
    Ok(output)
}

/// Audit a contract and generate one language using the bundled native core.
///
/// Every native allocation is released, including invalid UTF-8 results.
/// Missing or invalid contracts fail the build instead of falling back to env.
pub fn generate_types(
    config: &Path,
    language: Language,
    type_name: &str,
) -> Result<String, Box<dyn Error>> {
    let mut name_chars = type_name.chars();
    if !name_chars
        .next()
        .is_some_and(|c| c.is_ascii_alphabetic() || c == '_')
        || !name_chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
    {
        return Err("type name must be an ASCII identifier".into());
    }
    let config = config.to_str().ok_or("contract path must be UTF-8")?;
    // This call also retains the Rust runtime's bundled native linkage.
    flags2env::BundledFlags2Env::new().audit_config(Some(config))?;
    let rust_output = matches!(language, Language::Rust);
    let config = CString::new(config)?;
    let language = CString::new(match language {
        Language::Rust => "rust",
        Language::JsonSchema => "json-schema",
    })?;
    let type_name = CString::new(type_name)?;
    // SAFETY: live NUL-terminated inputs; the bundled core owns the returned
    // allocation and specifies f2e_free as its corresponding deallocator.
    let raw = unsafe {
        f2e_generate_types_from_file(config.as_ptr(), language.as_ptr(), type_name.as_ptr())
    };
    if raw.is_null() {
        return Err("flags2env native type generation returned no result".into());
    }
    // SAFETY: successful native results are NUL-terminated owned strings.
    let output = unsafe { CStr::from_ptr(raw) }.to_str().map(str::to_owned);
    // SAFETY: release exactly once, after copying or recording a UTF-8 error.
    unsafe { f2e_free(raw) };
    let output = output?;
    if output.trim().is_empty() {
        return Err("flags2env generated an empty type definition".into());
    }
    if rust_output {
        coalesce_compatible_rust_fields(&output)
    } else {
        Ok(output)
    }
}

/// Generate build products into a caller-owned output directory.
///
/// The embedded contract and generated fields come from one audited input.
/// Generated files belong in Cargo's OUT_DIR, not in a hand-edited source tree.
pub fn generate_into(
    config: &Path,
    output_dir: &Path,
    type_name: &str,
) -> Result<GeneratedFiles, Box<dyn Error>> {
    let rust = generate_types(config, Language::Rust, type_name)?;
    let schema = generate_types(config, Language::JsonSchema, type_name)?;
    let contract = fs::read(config)?;
    fs::create_dir_all(output_dir)?;
    let files = GeneratedFiles {
        rust: output_dir.join("cli_config.rs"),
        schema: output_dir.join("cli_config.schema.json"),
        contract: output_dir.join("cli-flags.toml"),
    };
    fs::write(&files.rust, rust)?;
    fs::write(&files.schema, schema)?;
    fs::write(&files.contract, contract)?;
    Ok(files)
}

/// Cargo build-script entry point. Prints only Cargo build instructions.
///
/// ```no_run
/// fn main() -> Result<(), Box<dyn std::error::Error>> {
///     flags2env_build::generate_cargo(".cli-flags.toml", "CliConfig")?;
///     Ok(())
/// }
/// ```
pub fn generate_cargo(
    config: impl AsRef<Path>,
    type_name: &str,
) -> Result<GeneratedFiles, Box<dyn Error>> {
    let config = config.as_ref();
    println!("cargo:rerun-if-changed={}", config.display());
    let output = std::env::var_os("OUT_DIR").ok_or("Cargo did not set OUT_DIR")?;
    generate_into(config, Path::new(&output), type_name)
}
